<center>
    <img src="https://gitlab.com/ibm/skills-network/courses/placeholder101/-/raw/master/labs/module%201/images/IDSNlogo.png" width="300" alt="cognitiveclass.ai logo"  />
</center>

# **Data Wrangling Lab**

Estimated time needed: **45 to 60** minutes

In this assignment you will be performing data wrangling.

## Objectives

In this lab you will perform the following:

*   Identify duplicate values in the dataset.

*   Remove duplicate values from the dataset.

*   Identify missing values in the dataset.

*   Impute the missing values in the dataset.

*   Normalize data in the dataset.

<hr>

## Hands on Lab

Import pandas module.

In [ ]:
import pandas as pd

Load the dataset into a dataframe.

In [ ]:
df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DA0321EN-SkillsNetwork/LargeData/m1_survey_data.csv")
df.head(3)

   Respondent  ...                  SurveyEase
0           4  ...                        Easy
1           9  ...  Neither easy nor difficult
2          13  ...                        Easy

[3 rows x 85 columns]

## Finding duplicates

In this section you will identify duplicate values in the dataset.

Find how many duplicate rows exist in the dataframe.

In [ ]:
# your code goes here
duplicate = df.duplicated().sum()
#print('the number of duplicate rows is:', duplicate.count())
duplicate
#df['Respondent'].duplicated().sum()

0

## Removing duplicates

Remove the duplicate rows from the dataframe.

In [ ]:
# your code goes here
#df.drop_duplicates(inplace = True)
df['CompFreq'].nunique()

3

Verify if duplicates were actually dropped.

In [ ]:
# your code goes here
#df.duplicated().sum()
#print('the number of blank rows in EdLevel column is:', df['EdLevel'].isnull().sum())
#print('the number of blank rows in Country column is:', df['Country'].isnull().sum())

#df['Employment'].value_counts()
#df['UndergradMajor'].value_counts()
#df['CompFreq'].value_counts()
df['NormalizedAnnualCompensation'].median()

100000.0

## Finding Missing values

Find the missing values for all columns.

In [ ]:
# your code goes here
df.isnull()

       Respondent  MainBranch  Hobbyist  ...  Dependents  SurveyLength  SurveyEase
0           False       False     False  ...       False         False       False
1           False       False     False  ...       False         False       False
2           False       False     False  ...       False         False       False
3           False       False     False  ...       False         False       False
4           False       False     False  ...       False         False       False
...           ...         ...       ...  ...         ...           ...         ...
11547       False       False     False  ...       False         False       False
11548       False       False     False  ...       False         False       False
11549       False       False     False  ...       False         False       False
11550       False       False     False  ...       False         False       False
11551       False       False     False  ...       False         False       False

[11398 rows x 85 columns]

Find out how many rows are missing in the column 'WorkLoc'

In [ ]:
# your code goes here
df['WorkLoc'].isnull().sum()

32

## Imputing missing values

Find the  value counts for the column WorkLoc.

In [ ]:
# your code goes here
df['WorkLoc'].isnull().value_counts()

False    11366
True        32
Name: WorkLoc, dtype: int64

Identify the value that is most frequent (majority) in the WorkLoc column.

In [ ]:
#make a note of the majority value here, for future reference
#
df['WorkLoc'].value_counts()

Office                                            6806
Home                                              3589
Other place, such as a coworking space or cafe     971
Name: WorkLoc, dtype: int64

Impute (replace) all the empty rows in the column WorkLoc with the value that you have identified as majority.

In [ ]:
# your code goes here
import numpy as np
df['WorkLoc'].replace(np.nan, 'Office', inplace = True)

After imputation there should ideally not be any empty rows in the WorkLoc column.

Verify if imputing was successful.

In [ ]:
# your code goes here
df['WorkLoc'].isnull().sum()

0

## Normalizing data

There are two columns in the dataset that talk about compensation.

One is "CompFreq". This column shows how often a developer is paid (Yearly, Monthly, Weekly).

The other is "CompTotal". This column talks about how much the developer is paid per Year, Month, or Week depending upon his/her "CompFreq".

This makes it difficult to compare the total compensation of the developers.

In this section you will create a new column called 'NormalizedAnnualCompensation' which contains the 'Annual Compensation' irrespective of the 'CompFreq'.

Once this column is ready, it makes comparison of salaries easy.

<hr>

List out the various categories in the column 'CompFreq'

In [ ]:
# your code goes here
df['CompFreq'].value_counts()

Yearly     6073
Monthly    4788
Weekly      331
Name: CompFreq, dtype: int64

Create a new column named 'NormalizedAnnualCompensation'. Use the hint given below if needed.

Double click to see the **Hint**.

<!--

Use the below logic to arrive at the values for the column NormalizedAnnualCompensation.

If the CompFreq is Yearly then use the exising value in CompTotal
If the CompFreq is Monthly then multiply the value in CompTotal with 12 (months in an year)
If the CompFreq is Weekly then multiply the value in CompTotal with 52 (weeks in an year)

-->

In [ ]:
# your code goes here
df.loc[df['CompFreq'] == 'Yearly', 'NormalizedAnnualCompensation'] = 1 * df['CompTotal']

df.loc[df['CompFreq'] == 'Monthly', 'NormalizedAnnualCompensation'] = 12 * df['CompTotal']

df.loc[df['CompFreq'] == 'Weekly', 'NormalizedAnnualCompensation'] = 52 * df['CompTotal']

df[['CompTotal', 'CompFreq', 'NormalizedAnnualCompensation']].head(20)

    CompTotal CompFreq  NormalizedAnnualCompensation
0     61000.0   Yearly                       61000.0
1    138000.0   Yearly                      138000.0
2     90000.0   Yearly                       90000.0
3     29000.0  Monthly                      348000.0
4     90000.0   Yearly                       90000.0
5      9500.0  Monthly                      114000.0
6      3000.0  Monthly                       36000.0
7    103000.0   Yearly                      103000.0
8     69000.0   Yearly                       69000.0
9      8000.0  Monthly                       96000.0
10     7000.0  Monthly                       84000.0
11   114000.0   Yearly                      114000.0
12     2000.0   Weekly                      104000.0
13    22000.0   Weekly                     1144000.0
14    96000.0  Monthly                     1152000.0
15   156000.0   Yearly                      156000.0
16    18000.0   Yearly                       18000.0
17     6400.0  Monthly                       76800.0
18     5000.0  Monthly                       60000.0
19   400000.0   Yearly                      400000.0

## Authors

Ramesh Sannareddy

### Other Contributors

Rav Ahuja

## Change Log

| Date (YYYY-MM-DD) | Version | Changed By        | Change Description                 |
| ----------------- | ------- | ----------------- | ---------------------------------- |
| 2020-10-17        | 0.1     | Ramesh Sannareddy | Created initial version of the lab |

Copyright Â© 2020 IBM Corporation. This notebook and its source code are released under the terms of the [MIT License](https://cognitiveclass.ai/mit-license?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDA0321ENSkillsNetwork21426264-2021-01-01&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBM-DA0321EN-SkillsNetwork-21426264&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ).